name = "user-mgmt"
main = "src/index.ts"
compatibility_date = "2024-01-17"


[[services]]
binding = "sessionService"
service = "session-state"

[[d1_databases]]
binding = "web-dor"
database_name = "users"
database_id = "c1e0dccd-a96e-438d-8efa-1baca59d3b54"

[vars]
EMAIL_FROM = "noreply@justblackmagic.com"
EMAIL_FROM_NAME = "Black Magic Consulting"

EMAIL_DKIM_SELECTOR = "mailchannels"
EMAIL_DKIM_DOMAIN = "c-bnn.xyz"
FORGOT_PASSWORD_URL = "https://account-pages.tools.x-bnn.xyz/forgot-password-reset.html"
TOKEN_VALID_MINUTES = 60

[dev]
port = 51512
